import { type Metadata } from 'next';
import { Space_Mono } from 'next/font/google';
import React from 'react';
import './globals.css';
import { StoreProvider } from '@/providers';

const monospace = Space_Mono({ weight: ['400', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={monospace.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
